### PR TITLE
Remove extra parentheses

### PR DESCRIPTION
**Pull request by persianpros**
With this my build is just fine on Ubuntu 18.04 LTS.

### CODE REVIEW

**Comment by eriksl** [comment]
I would call this "Remove superfluous parenthesis that causes syntax error"....

It has nothing to do with the building environment.

Add to that, it should have been detected before submitting the original patch, solving syntax errors in a seperate commit is considered ugly.

**Comment by persianpros** [comment]
@eriksl 
Yeah you're right, I'm really sorry for this.
May I ask you to do something?
Please remove this repo for like 1 minute and import this one with only the correct commit: https://github.com/persianpros/servicemp3
via http://import.github.com so we don't see these fixes.

**Comment by persianpros** [comment]
@eriksl 
Or please rebase master on https://github.com/OpenPLi/servicemp3/commit/d9a83ce0525fba1a0f4c59e67a1e4cf968578a2f then I'll add the correct commit.

I can fix this ASAP if I have access to this repo for only 5 minutes.

Again sorry for any inconvenience :(

**Comment by eriksl** [comment]
We can't rebase public repositories (and similarly not redraw/unpublish and publish it again), that would break all build environments that rely on it.

So please add a proper fix commit and in the future test it before making the PR.

**Pull request closed without merging**
