### PR TITLE
[Updated] Optimized DVB subtitles handling code

### PR DESCRIPTION
**Pull request by DimitarCC**

### CODE REVIEW

**Comment by WanWizard** [comment]
Untested ?
````
ERROR: Logfile of failure stored in: /openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/temp/log.do_compile.2957129
Log data follows:
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing shell function do_compile
| NOTE: make -j 10
| Making all in servicemp3
| make[1]: Entering directory '/openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/build/servicemp3'
| ../mipsel-oe-linux-libtool  --tag=CXX   --mode=compile mipsel-oe-linux-g++  -mel -mabi=32 -mhard-float -march=mips32 --sysroot=/openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot -std=gnu++17 -DPACKAGE_NAME=\"servicemp3\" -DPACKAGE_TARN>
| mipsel-oe-linux-libtool: compile:  mipsel-oe-linux-g++ -mel -mabi=32 -mhard-float -march=mips32 --sysroot=/openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot -std=gnu++17 -DPACKAGE_NAME=\"servicemp3\" -DPACKAGE_TARNAME=\"servicemp3\" -D>
| ../../git/servicemp3/servicemp3.cpp: In constructor 'eServiceMP3::eServiceMP3(eServiceReference)':
| ../../git/servicemp3/servicemp3.cpp:451:56: error: no matching function for call to 'eDVBSubtitleParser::eDVBSubtitleParser()'
|   451 |         m_dvb_subtitle_parser = new eDVBSubtitleParser();
|       |                                                        ^
| In file included from /openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot/usr/include/enigma2/lib/gui/esubtitle.h:7,
|                  from ../../git/servicemp3/servicemp3.cpp:12:
| /openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot/usr/include/enigma2/lib/dvb/subtitle.h:124:9: note: candidate: 'eDVBSubtitleParser::eDVBSubtitleParser(iDVBDemux*)'
|   124 |         eDVBSubtitleParser(iDVBDemux *demux);
|       |         ^~~~~~~~~~~~~~~~~~
| /openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot/usr/include/enigma2/lib/dvb/subtitle.h:124:9: note:   candidate expects 1 argument, 0 provided
| /openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot/usr/include/enigma2/lib/dvb/subtitle.h:111:7: note: candidate: 'eDVBSubtitleParser::eDVBSubtitleParser(const eDVBSubtitleParser&)'
|   111 | class eDVBSubtitleParser
|       |       ^~~~~~~~~~~~~~~~~~
| /openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/recipe-sysroot/usr/include/enigma2/lib/dvb/subtitle.h:111:7: note:   candidate expects 1 argument, 0 provided
| ../../git/servicemp3/servicemp3.cpp: In member function 'void eServiceMP3::gstBusCall(GstMessage*)':
| ../../git/servicemp3/servicemp3.cpp:1778:31: warning: enumeration value 'GST_STATE_CHANGE_NULL_TO_READY' not handled in switch [-Wswitch]
|  1778 |                         switch(transition)
|       |                               ^
| ../../git/servicemp3/servicemp3.cpp:1778:31: warning: enumeration value 'GST_STATE_CHANGE_READY_TO_NULL' not handled in switch [-Wswitch]
| ../../git/servicemp3/servicemp3.cpp:1778:31: warning: enumeration value 'GST_STATE_CHANGE_NULL_TO_NULL' not handled in switch [-Wswitch]
| ../../git/servicemp3/servicemp3.cpp:1778:31: warning: enumeration value 'GST_STATE_CHANGE_READY_TO_READY' not handled in switch [-Wswitch]
| ../../git/servicemp3/servicemp3.cpp:1778:31: warning: enumeration value 'GST_STATE_CHANGE_PAUSED_TO_PAUSED' not handled in switch [-Wswitch]
| ../../git/servicemp3/servicemp3.cpp:1778:31: warning: enumeration value 'GST_STATE_CHANGE_PLAYING_TO_PLAYING' not handled in switch [-Wswitch]
| ../../git/servicemp3/servicemp3.cpp: In member function 'void eServiceMP3::pullSubtitle(GstBuffer*)':
| ../../git/servicemp3/servicemp3.cpp:2633:56: error: 'class eDVBSubtitleParser' has no member named 'processBuffer'
|  2633 |                                 m_dvb_subtitle_parser->processBuffer(data, len, buf_pos / 1000000ULL);
|       |                                                        ^~~~~~~~~~~~~
| make[1]: Leaving directory '/openpli/oe/develop/build/tmp/work/et6x00-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+b25e8548b3-r0/build/servicemp3'
````

**Comment by DimitarCC** [comment]
Well. Enigma have to be built first with the new changes for DVB subs and then servicemp3 because it depends on it....

**Comment by WanWizard** [comment]
Probably just checked the logs at the wrong time... ;)

The current build run seems to go fine.

**Comment by littlesat** [comment]
Thanks for always port such things to us!!!

**Pull request merged**
